export const evaluationsLocal = [
    {
      name: 'Mark Foster',
      title: 'Technik/Individualtraining mit Ball',
      quality: '2',
      planned: '3',
      achieved: '2',
      comments: '',
      start_time: '17:52:00',
      end_time: '17:53:00',
      date: '2022-05-15T22:00:00.000Z',
      as_planned: true,
      difference: '1'
    },
    {
      name: 'Mark Foster',
      title: 'Technik/Individualtraining mit Ball',
      quality: '2',
      planned: '3',
      achieved: '1',
      comments: '',
      start_time: '17:52:00',
      end_time: '17:53:00',
      date: '2022-04-15T22:00:00.000Z',
      as_planned: true,
      difference: '1'
    },
    {
      name: 'Mark Foster',
      title: 'Ausdauerübungen',
      quality: '2',
      planned: '3',
      achieved: '2',
      comments: 'Well done!',
      start_time: '17:52:00',
      end_time: '17:53:00',
      date: '2022-05-25T22:00:00.000Z',
      as_planned: true,
      difference: '1'
    },
    {
      name: 'Mark Foster',
      title: 'Technik/Individualtraining mit Ball',
      quality: '2',
      planned: '3',
      achieved: '3',
      comments: '',
      start_time: '17:52:00',
      end_time: '17:53:00',
      date: '2022-05-01T22:00:00.000Z',
      as_planned: true,
      difference: '1'
    },
    {
      name: 'Mark Foster',
      title: 'Technik/Individualtraining mit Ball',
      quality: '2',
      planned: '3',
      achieved: '1',
      comments: '',
      start_time: '17:52:00',
      end_time: '17:53:00',
      date: '2022-05-01T22:00:00.000Z',
      as_planned: true,
      difference: '1'
    },
    {
      name: 'John Foster',
      title: 'Ausdauerübungen',
      quality: '5',
      planned: '5',
      achieved: '5',
      comments: 'good',
      start_time: '17:58:00',
      end_time: '17:58:00',
      date: '2022-05-16T22:00:00.000Z',
      as_planned: true,
      difference: '0'
    },
    {
      name: 'Martin Foster',
      title: 'Reflex bauen',
      quality: '3',
      planned: '2',
      achieved: '2',
      comments: 'he is too tired',
      start_time: '17:46:00',
      end_time: '17:46:00',
      date: '2022-05-17T22:00:00.000Z',
      as_planned: false,
      difference: '0'
    },
    {
      name: 'Marie Foster',
      title: 'Technik/Individualtraining mit Ball',
      quality: '3',
      planned: '2',
      achieved: '2',
      comments: 'he is too tired',
      start_time: '17:46:00',
      end_time: '17:46:00',
      date: '2022-05-18T22:00:00.000Z',
      as_planned: false,
      difference: '0'
    },
    {
      name: 'Adam Foster',
      title: 'Technik/Individualtraining mit Ball',
      quality: '3',
      planned: '2',
      achieved: '2',
      comments: 'he is too tired',
      start_time: '17:46:00',
      end_time: '17:46:00',
      date: '2022-05-19T22:00:00.000Z',
      as_planned: false,
      difference: '0'
    },
    {
      name: 'John Foster',
      title: 'Technik/Individualtraining mit Ball',
      quality: '5',
      planned: '5',
      achieved: '5',
      comments: 'good',
      start_time: '17:58:00',
      end_time: '17:58:00',
      date: '2022-05-20T22:00:00.000Z',
      as_planned: true,
      difference: '0'
    },
    {
      name: 'Martin Foster',
      title: 'Technik/Individualtraining mit Ball',
      quality: '3',
      planned: '2',
      achieved: '2',
      comments: 'he is too tired',
      start_time: '17:46:00',
      end_time: '17:46:00',
      date: '2022-05-21T22:00:00.000Z',
      as_planned: false,
      difference: '0'
    },
    {
      name: 'Marie Foster',
      title: 'Technik/Individualtraining mit Ball',
      quality: '3',
      planned: '2',
      achieved: '2',
      comments: 'he is too tired',
      start_time: '17:46:00',
      end_time: '17:46:00',
      date: '2022-05-22T22:00:00.000Z',
      as_planned: false,
      difference: '0'
    },
    {
      name: 'Adam Foster',
      title: 'Technik/Individualtraining mit Ball',
      quality: '3',
      planned: '2',
      achieved: '2',
      comments: 'he is too tired',
      start_time: '17:46:00',
      end_time: '17:46:00',
      date: '2022-05-23T22:00:00.000Z',
      as_planned: false,
      difference: '0'
    }
  ];

  export const evaluationsHeadCells = [
    {
      id: 'name',
      numeric: false,
      label: 'Name',
      tableView: true,
    },
    {
      id: 'title',
      numeric: false,
      label: 'Titel',
      tableView: true,
    },
    {
      id: 'quality',
      numeric: true,
      label: 'Qualität',
      tableView: false,
    },
    {
        id: 'planned',
        numeric: true,
        label: 'Geplant',
        tableView: false,
      }, 
      {
        id: 'achieved',
        numeric: true,
        label: 'Erreicht',
        tableView: true,
      },
      {
        id: 'comments',
        numeric: false,
        label: 'Kommentare',
        tableView: true,
      },
      {
        id: 'start_time',
        numeric: false,
        label: 'Startzeit',
        tableView: false,
      },
      {
        id: 'end_time',
        numeric: false,
        label: 'Endzeit',
        tableView: false,
      },
      {
        id: 'date',
        numeric: false,
        label: 'Datum',
        tableView: true,
      },
      {
        id: 'as_planned',
        numeric: true,
        label: 'Wie geplant',
        tableView: false,
      },
      {
        id: 'difference',
        numeric: true,
        label: 'Differenz',
        tableView: true,
      }, 
      
  ];